### ISSUE TITLE
Open-Meteo integration

### ISSUE THREAD

**Issue by open-meteo** [striezel/weather-information-collector#1]
Hi,

I just saw you project while looking for documentation about darksky api. I really liked your documentation for dark sky at https://github.com/striezel/weather-information-collector/blob/master/src/api/darksky.md Because it is about to shut down, there is barely any good information left.

You mentioned in your list of improvements that you want to add more data provider. I created a free weather API that could be a candidate for that: https://open-meteo.com 

Would you be interested to integrate it? Let me know if you need some additional weather variables or different syntax for location selection.

Best, Jeff

**Comment by striezel** [comment]
> I just saw you project while looking for documentation about darksky api. I really liked your documentation for dark sky at https://github.com/striezel/weather-information-collector/blob/master/src/api/darksky.md Because it is about to shut down, there is barely any good information left.

Thanks.

I deliberately documented all the APIs that I am using here, because one never knows when the documentation on the original site changes or - in the worst case - vanishes. So I can still see what endpoints are available and what kind of data they provide, even if the API authors remove the documentation on their site. (I have seen that at least once: New version of an API comes out, old version of the API is still active, but all documentation for it is removed and only the documentation for the new version is available.) DarkSky has been pushing the shutdown date back already, original date was "end of 2021". Now it's March 2023.

Minor drawback: I only documented those parts of the DarkSky API that I am actually using in this project. They still have/had more endpoints for other data, but I did not care about those.

> You mentioned in your list of improvements that you want to add more data provider. I created a free weather API that could be a candidate for that: https://open-meteo.com
> 
> Would you be interested to integrate it?

Not sure.

I am usually looking for data providers that provide both forecast data (i. e.: what will the weather be like in a few hours or days) and current weather data (i. e.: what is the weather right now). So far Open-Meteo seems to provide forecast data only. Any chance that there will be current weather data, too?

> Let me know if you need some additional weather variables or different syntax for location selection.

Location selection via longitude and latitude is fine.

I'd basically like to have the following weather variables:
* temperature (preferably in Celsius, but others are okay, I can convert them)
* relative humidity
* precipitation: amount, and preferably an indicator to distinguish between rain and snow
* air pressure
* wind speed and wind direction
* cloudiness / cloud coverage

As far as I can tell, all of them are present in Open-Meteo, except for the rain/snow distinction. Is it possible to add that?

**Comment by open-meteo** [comment]
> I am usually looking for data providers that provide both forecast data (i. e.: what will the weather be like in a few hours or days) and current weather data (i. e.: what is the weather right now). So far Open-Meteo seems to provide forecast data only. Any chance that there will be current weather data, too?

Yes, I am planning to integrate more current data in the future. The current option for `current` data is mostly a placeholder and uses the most recent forecast as current. With 3-hourly weather models update, it is actually not too bad. As soon as more real-time data is available, it will be transparently integrated there. 

My current focus is on archiving forecasts with seamless integration into forecast data. E.g. 90 days past weather data with 7 days of forecast in one go. 

> As far as I can tell, all of them are present in Open-Meteo, except for the rain/snow distinction. Is it possible to add that?

Good point. It is possible by checking the weather code for snow, but this is counter intuitive. I will add an additional variable `snowfall` to make it simpler.

**Comment by open-meteo** [comment]
Snowfall (along with convective rain) have been added to open-meteo!

**Comment by striezel** [comment]
OK.

So if I understand this corretly, then the total rain amount is basically the sum of `rain` and `showers` from that API. And snow amount is just `snowfall` now, right? Furthermore, `precipitation` is the sum of `rain` and `showers` and `snowfall`, according to the documentation.

However, I find it a bit confusing / inconsistent sometimes. An example for that is shown in those two pictures.

First picture:
* showers: zero
* rain: zero
* snowfall: 0.1 cm
* precipitation: **0.1 mm**

![precip](https://user-images.githubusercontent.com/20865852/173412141-d9dde3e7-5aae-4f02-870d-4b02c641efc3.png)

Second picture, from the same graph:
* showers: zero
* rain: zero
* snowfall: 0.1 cm
* precipitation: **0.2 mm**

![precip2](https://user-images.githubusercontent.com/20865852/173412142-ac53e9d4-6bda-4004-8bd6-0e2d7c12d7d6.png)

So showers, rain and snowfall stay the same, but precipitation - which is just the sum of those three - suddenly goes up. How can that be?

_PS:_ Seems like a bug in Open-Meteo to me. Do you prefer that I open a new issue at the Open-Meteo repository for that?

**Comment by open-meteo** [comment]
Thanks for checking! 

Correct, `precipitation = rain + showers + snow`. 

I guess the confusion is coming from different units for snow in `cm` and precipitation in `mm`. To convert precipitation to snow, a fixed factor of 7 is applied. `0.1 mm` precipitation equals `0.7 mm` snow (rounded to `0.1 cm`). `0.2 mm` precipitation equals `1.4 mm` snow (rounded to `0.1 cm`). With conversion and rounding, you only see `0.1 cm` and `0.2 cm`. 

I decided to use `cm` for snow to make it a bit clearer and avoid confusion with snow water equivalent which has no conversion factor of 7 applied.

To improve the situation, I use now 2 significant digits for snow to show `0.07 cm` and `0.14 cm`.

What do you think?

**Comment by striezel** [comment]
The rounding was the source of the confusion here. Otherwise it would have been clear that the `snowfall` value changed, too.

So I think it should have all things that are needed and I could start using it. But don't expect any work from that before the weekend.

**Comment by striezel** [comment]
It took a while, but it's done now. The new [version 0.10.0](https://github.com/striezel/weather-information-collector/releases/tag/v0.10.0) supports Open-Meteo API calls.

For those interested in the (not completely trivial) changes see https://github.com/striezel/weather-information-collector/compare/66f21d7d100fa95b2219d1c9447fc143d7a1db85...86d95043f09e1d502a35b5a0f78f8011fd2fc2bf.
